### ISSUE TITLE
Not showing latest Power and Politics episode

### ISSUE THREAD

**Issue by brianjmurrell** [micahg/plugin.video.cbc#7]
Hi.

Just noticed that even though https://www.cbc.ca/news/politics/powerandpolitics shows a "Jan. 6: Canadian defence minister says Canada wants to continue its mission Iraq" episode, your plugin is only showing up to "Jan. 3: U.S. airstrikes kill Iranian General Qassem Soleimani".

**Comment by micahg** [comment]
Hi @brianjmurrell,

I'm wondering if there was a delay maybe because I just tested and see the episodes. A few things to keep in mind. The source data of https://www.cbc.ca/news/politics/powerandpolitics is not the same as https://gem.cbc.ca/series/power-politics-with-vassy-kapelos/all/96b0e596-4eb4-41c1-a90f-144ec9251361.  This addon uses the CBC GEM infrastructure.

If you're still having trouble can you tell me what you see at https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/96b0e596-4eb4-41c1-a90f-144ec9251361? It should have the 6th and the 7th.

**Comment by brianjmurrell** [comment]
Seems to be OK now I think.

**Comment by micahg** [comment]
thanks
